### ISSUE TITLE
ABAT network  in package needs to be updated: 'succinamide' to 'succinamic acid'.

### ISSUE THREAD

**Issue by Xiqi-Li** [BRL-BCM/CTD#7]
ABAT network  in package needs to be updated: 'succinamide' to 'succinamic acid'.

**Comment by lashmore** [comment]
Fixed with below code:

rm(list=ls())
load(system.file("networks/bg_aadc_maps_naive.RData", package="CTD"))
V(ig_pruned)$name[grep("succin", V(ig_pruned)$name)]
V(ig_pruned)$name[grep("succinimide", V(ig_pruned)$name)] = "succinamic acid"
V(ig_pruned)$name[grep("succin", V(ig_pruned)$name)]
save.image("/Users/lillian.rosa/Downloads/CTD/inst/networks/bg_aadc_maps_naive.RData")

rm(list=ls())
load(system.file("networks/bg_abat_maps_naive.RData", package="CTD"))
V(ig_pruned)$name[grep("succin", V(ig_pruned)$name)]
V(ig_pruned)$name[grep("succinimide", V(ig_pruned)$name)] = "succinamic acid"
V(ig_pruned)$name[grep("succin", V(ig_pruned)$name)]
save.image("/Users/lillian.rosa/Downloads/CTD/inst/networks/bg_abat_maps_naive.RData")

rm(list=ls())
load(system.file("networks/bg_adsl_maps_naive.RData", package="CTD"))
V(ig_pruned)$name[grep("succin", V(ig_pruned)$name)]
V(ig_pruned)$name[grep("succinimide", V(ig_pruned)$name)] = "succinamic acid"
V(ig_pruned)$name[grep("succin", V(ig_pruned)$name)]
save.image("/Users/lillian.rosa/Downloads/CTD/inst/networks/bg_adsl_maps_naive.RData")
